# Generated by Django 2.1.5 on 2019-05-23 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0002_auto_20190518_2349'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='movie',
            unique_together=set(),
        ),
    ]
