# Generated by Django 2.1.5 on 2019-01-27 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_question_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('release_year', models.CharField(max_length=4)),
                ('user_rating', models.IntegerField(default=0)),
            ],
        ),
    ]
