# Generated by Django 2.1.5 on 2019-01-27 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_movie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie_Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0)),
                ('applies_to_user', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='movie',
            name='user_rating',
        ),
        migrations.AddField(
            model_name='movie_rating',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Movie'),
        ),
    ]
