# Generated by Django 2.1.5 on 2019-01-27 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20190127_1823'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0)),
                ('user', models.CharField(max_length=200)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Movie')),
            ],
        ),
        migrations.RemoveField(
            model_name='movie_rating',
            name='movie',
        ),
        migrations.DeleteModel(
            name='Movie_Rating',
        ),
    ]
