# Generated by Django 2.1.5 on 2019-01-27 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_userrating'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='movie',
            unique_together={('title', 'release_year')},
        ),
    ]
