# Generated by Django 2.1.5 on 2019-01-27 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20190127_2215'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userrating',
            unique_together={('movie', 'user_name')},
        ),
    ]
